### PR TITLE
Use docsy as theme

### PR DESCRIPTION
**Pull request by niwo**
- use the docsy the (and docy-plus, docsy-puzzle) as the newest puzzle and acend trainings do
- using the "details" shortcode from docy-plus instead of "collapsible"
- adapting labs and other contents to look good with the new theme
- adapt README to reflect the theme changes

### CODE REVIEW

**Comment by ombre8** [comment]
Hi @niwo I just built a container and clicked around a bit... looks good to me, just one lil issue, the edit  Button of a page leads to a 404 Error on Github:
Link on Page: https://github.com/puzzle/ansible-techlab/edit/master/content/en/docs/01/_index.en.md
Should be: https://github.com/puzzle/ansible-techlab/edit/master/content/labs/01.0/_index.en.md
Could you fix that? Or shall I look into it?

**Comment by niwo** [comment]
> Hi @niwo I just built a container and clicked around a bit... looks good to me, just one lil issue, the edit Button of a page leads to a 404 Error on Github:
> Link on Page: https://github.com/puzzle/ansible-techlab/edit/master/content/en/docs/01/_index.en.md
> Should be: https://github.com/puzzle/ansible-techlab/edit/master/content/labs/01.0/_index.en.md
> Could you fix that? Or shall I look into it?

Thanks for looking at it @ombre8 ! I'll take a look at the edit button.

**Comment by niwo** [comment]
@ombre8 Just checked: The link is actually correct and reflects the folder structure from the docsy-theme branch. You are getting a 404 because the master (which is referenced) branch still hold the old structure.

**Review by ombre8 — APPROVED** [review]
Sorry about that, LGTM

**Pull request merged**
